/* generated by gxr: '../../util/gxr/gxr-gen.rb blogger blogger.gxr'. */

#ifndef BLOGGER_H
#define BLOGGER_H

#include <gxr.h>



const char * blogger_newPost(GXRContext *ctx, const char * arg_appkey, const char * arg_journal, const char * arg_user, const char * arg_password, const char * arg_content, gboolean arg_publish, GError **err);
gboolean blogger_deletePost(GXRContext *ctx, const char * arg_appkey, const char * arg_postId, const char * arg_user, const char * arg_password, gboolean arg_publish, GError **err);
int blogger_editPost(GXRContext *ctx, const char * arg_appkey, const char * arg_postId, const char * arg_user, const char * arg_password, const char * arg_content, gboolean arg_publish, GError **err);

#endif /* BLOGGER_H */
