/* autogenerated by gen.pl. */
char *helptext_commands = N_(
"Commands:\n"
"  post            Post event immediately.\n"
"  sync            Synchronize offline journal.\n"
"  checkfriends    Efficiently check friends list for updates.\n"
"  cat             Dump entries to stdout.\n"
"  grep            Grep through entries.\n"
"  reindex         Rebuild offline index.\n"
);

char *helptext_options = N_(
"Command line options:\n"
"  -h, --help                 Show summary of options.\n"
"  -v, --version              Show version of program.\n"
"  -q, --quiet                Say less.\n"
"  -c, --console              Don't load GUI.\n"
"\n"
"  -u, --username=USERNAME    Username to operate as.\n"
"  -U, --save-username        Save the username.\n"
"  -p, --password=PASSWORD    Password for the current user.\n"
"  -P, --save-password        Save the password.\n"
"  -n, --no-login             Use with -u to start without logging in.\n"
"\n"
"  -s, --subject=SUBJECT      Subject for the post.\n"
"  -a, --postas=USERNAME      User/community to post as.\n"
"  -k, --userpic=KEYWORD      Keyword for the user picture to use.\n"
"  -e, --edit                 Use default editor to edit post.\n"
);
