/* autogenerated by thanks.pl. */
typedef struct {
	char *name;
	char *username;
	char *email;
	char *contribution;
} Contributor;

Contributor contribs[] = {
	/* this translation is not crucial */
	{ "Aleksander Adamowski", "", "aleksander.adamowski@gmail.com", N_("patches") },
	/* this translation is not crucial */
	{ "Satoru SATOH", "", "ss@gnome.gr.jp", N_("Japanese translation") },
	/* this translation is not crucial */
	{ "Grigory Bakunov", "", "black@asplinux.ru", N_("Russian translation") },
	/* this translation is not crucial */
	{ "Frank Hofmann", "", "frankhofmann@gmx.ch", N_("German translation") },
	/* this translation is not crucial */
	{ "George Mason", "", "georgemason@mindspring.com", N_("accelerator saving") },
	/* this translation is not crucial */
	{ "Dave Spadea", "", "dave@spadea.net", N_("lj-cut patch") },
	/* this translation is not crucial */
	{ "Dmitry Dyomin", "old_one", "old@old.com.ua", N_("Ukrainian translation") },
	/* this translation is not crucial */
	{ "Ricardo Mones Lastra", "mones", "ricardo.mones@hispalinux.es", N_("Spanish translation") },
	/* this translation is not crucial */
	{ "Jon Nall", "", "nall@gentoo.org", N_("Gentoo packaging") },
	/* this translation is not crucial */
	{ "Mikhail Chekanov", "", "mihun@bitex.com", N_("Russian translation") },
	/* this translation is not crucial */
	{ "Asaf Bartov", "ijon", "ijon@forum2.org", N_("win32 multithread support") },
	/* this translation is not crucial */
	{ "Gaal Yahas", "gaal", "gaal@forum2.org", N_("checkfriends, poll creator, i18n") },
	/* this translation is not crucial */
	{ "Sergei Barbarash", "sgt", "sgt@fep.ru", N_("support for cyrillic translation") },
	/* this translation is not crucial */
	{ "Michael Bravo", "", "mbravo@tag-ltd.spb.ru", N_("locale fixes") },
	/* this translation is not crucial */
	{ "Ari Pollak", "", "ari@debian.org", N_("Debian package, undo") },
	/* this translation is not crucial */
	{ "Steve Bernacki, Jr.", "", "steve@copacetic.net", N_("typo in configure.in") },
	/* this translation is not crucial */
	{ "Artem Baguinski", "", "artm@v2.nl", N_("locale setting") },
	/* this translation is not crucial */
	{ "nulld", "", "nulld@encryptedemail.net", N_("OpenBSD box to test on") },
	/* this translation is not crucial */
	{ "Decklin Foster", "decklin", "decklin@red-bean.com", N_("window geometry save/restore") },
	/* this translation is not crucial */
	{ "Matthew Vernon", "", "matthew@pick.ucam.org", N_("simple login proxy patch") },
	/* this translation is not crucial */
	{ "Bill Crawford", "", "bill@eb0ne.net", N_("variety of patches") },
	/* this translation is not crucial */
	{ "Gabriel Martinez", "diamondc", "gabrielfm@yahoo.com", N_("Solaris box to test on") },
	/* this translation is not crucial */
	{ "Tom Callaway", "spot", "spot@redhat.com", N_("Advanced RPM packaging") },
	/* this translation is not crucial */
	{ "Alexander Gräfe", "", "nachtfalke@retrogra.de", N_("Initial RPM packaging") },
	/* this translation is not crucial */
	{ "Christian Surchi", "christian", "csurchi@debian.org", N_("Debian maintainer") },
	/* this translation is not crucial */
	{ "Joe Wreschnig", "piman", "piman@sacredchao.net", N_("Debian package help") },
	/* this translation is not crucial */
	{ "Ryan Younce", "", "ryan@manunkind.org", N_("FreeBSD packaging") },
	/* this translation is not crucial */
	{ "Raja Mukerji", "", "mukerji@pobox.com", N_("a multitude of patches") },
	/* this translation is not crucial */
	{ "Adam Bidema", "", "hijinx@klone.nwraves.net", N_("initial file save patch") },
	/* this translation is not crucial */
	{ "Matt Roper", "", "mdroper@ucdavis.edu", N_("parallel make tips") },
	/* this translation is not crucial */
	{ "Brad Fitzpatrick", "", "brad@danga.com", N_("much of the original client") },
};

#define CONTRIBCOUNT 31
