#! /usr/bin/perl -w
# vim: ts=4 sw=4
use strict;

my $contribcount = 0;

# just so random CVS users know what's going on...

print "Generating thanks.h...\n";
open(THANKS, "../doc/README") or die $!;
open(HEADER, ">thanks.h") or die $!;

sub contribs {
	while (<THANKS>) {
		chomp;
		next if not (/^(.*?) <(.*?)> - (.*)$/);
		my $name = $1;
		my $email = $2;
		my $contrib = $3;
		my $username = "";
		if ($name =~ s/"(.*?)" //) {
			$username = $1;
		}
		print HEADER "\t/* this translation is not crucial */\n";
		print HEADER "\t{ \"$name\", \"$username\", \"$email\", N_(\"$contrib\") },\n";
		$contribcount++;
	}
}

print HEADER <<EOT;
/* autogenerated by thanks.pl. */
typedef struct {
	char *name;
	char *username;
	char *email;
	char *contribution;
} Contributor;

Contributor contribs[] = {
EOT
contribs();
print HEADER <<EOT;
};

#define CONTRIBCOUNT $contribcount
EOT
close(HEADER);
close(THANKS);

